name: Node.js CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.vladmaraev.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.vladmaraev.npmAlwaysAuth true
          yarn config set npmScopes.vladmaraev.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Publish to NPM registry
        run: yarn npm publish --tag 2.0.0-beta.${{ github.run_id }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
