name: Compile and package

on:
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.05

      - run: nix develop

      - run: yarn --immutable
      - run: yarn exec tsc
      - run: npm version prerelease --no-git-tag-version --preid=${{ format('pr{0}-{1}-{2}', github.event.number, github.run_attempt, github.run_id) }}

      - uses: actions/setup-node@v4       
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPM registry
        run: npm publish --tag ${{ format('pr{0}', github.event.number) }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

